---
title: "sigident - SVM/KNN/RF Example"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{sigident-SVM_example}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Prerequisites and installation 

Make sure, that both R packages, sigidnet.preproc and sigident, are installed.

## Initialization of important variables

```{r setup}
library(sigident)
library(sigident.preproc)
library(knitr)

rm(list=ls())

# initialize filePath:
filePath <- tempdir()

# define datadir
maindir <- "./geodata/"
datadir <- paste0(maindir, "data/")
dir.create(maindir)
dir.create(datadir)

# define plotdir
plotdir <- "./plots/"
dir.create(plotdir)

# define idtype
idtype = "affy"

# general
csvdir <- "./csv/"
dir.create(csvdir)

# diagnostic signature
seed <- 111
split <- 0.8
nfolds <- 10
```

# Apply SVM, KNN and RF Classifier

```{r eval=FALSE}
# Set variables
pathDiagnosis = "vignettes/diagnosis.csv"
pathMergeset = "vignettes/mergeset_100.csv"
seed <- 111
split <- 0.8
nfolds <- 10
plotdir <- "./plots/"
dir.create(plotdir)

# Read in small mergeset file (1 000 features instead of 54 000)
mergesetData <- read.csv(pathMergeset, header=TRUE, row.names=1)

# Read in diagnosis file
diagnosisData <- read.csv(pathDiagnosis, header=TRUE, row.names=1)
# diagnosis <- subset(diagnosis, select=c("a"))

# Create training list
training_list <- sigident::create_training_test_split(diagnosis = diagnosisData,
                                               mergeset = mergesetData,
                                               split = split,
                                               seed = seed)

# SVM
diagnostic_svm <- sigident::signature(traininglist = training_list,
                                         type = "svm",
                                         nfolds = nfolds,
                                         seed = seed)                                               
# KNN
diagnostic_knn <- sigident::signature(traininglist = training_list,
                                         type = "knn",
                                         nfolds = nfolds,
                                         seed = seed)
# Random Forest
diagnostic_rf <- sigident::signature(traininglist = training_list,
                                        type = "random_forest",
                                        nfolds = nfolds,
                                        seed = seed)


```

